# --- YAML Extension Field for NFS Volume Configuration ---
# Define the common NFS options once to avoid repetition.
# This makes maintenance significantly easier.
x-nfs-volume-opts: &nfs-volume-opts
  driver: local
  driver_opts:
    type: nfs
    # CRITICAL CHANGE: Using 'hard' mount instead of 'soft' to prevent data corruption.
    # Set to 'nfsvers=3' to match your server configuration.
    o: "addr=10.20.10.27,rw,hard,noatime,nfsvers=3"
    # 'device' will be overridden for each specific volume below.
    device: ":/path/to/be/overridden"

services:
#  ██████╗ ██╗     ██╗   ██╗███████╗████████╗██╗  ██╗███╗   ██╗
# ██╔════╝ ██║     ██║   ██║██╔════╝╚══██╔══╝██║  ██║████╗  ██║
# ██║  ███╗██║     ██║   ██║█████╗     ██║   ██║  ██║██╔██╗ ██║
# ██║   ██║██║     ██║   ██║██╔══╝     ██║   ██║  ██║██║╚██╗██║
# ╚██████╔╝███████╗╚██████╔╝███████╗   ██║   ╚██████╔╝██║ ╚████║
#  ╚═════╝ ╚══════╝ ╚═════╝ ╚══════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═══╝
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    ports:
      - 6789:6789      # NZBGet
      - 8080:8080      # QBittorrent
      - 6881:6881      # QBittorrent
      - 6881:6881/udp  # QBittorrent
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      -./gluetun-config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=openvpn
      - SERVER_COUNTRIES=Netherlands
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24,10.20.10.27/32
    restart: unless-stopped

# ███╗   ██╗███████╗██████╗  ██████╗ ███████╗████████╗
# ████╗  ██║╚══███╔╝██╔══██╗██╔════╝ ██╔════╝╚══██╔══╝
# ██╔██╗ ██║  ███╔╝ ██████╔╝██║  ███╗█████╗     ██║
# ██║╚██╗██║ ███╔╝  ██╔══██╗██║   ██║██╔══╝     ██║
# ██║ ╚████║███████╗██████╔╝╚██████╔╝███████╗   ██║
# ╚═╝  ╚═══╝╚══════╝╚═════╝  ╚═════╝ ╚══════╝   ╚═╝
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    network_mode: "service:gluetun"
    volumes:
      - nzbget_config:/config
      - downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'

# ██████╗ ██████╗ ██╗████████╗████████╗ ██████╗ ██████╗ ██████╗ ███████╗███╗   ██╗████████╗
# ██╔═══██╗██╔══██╗██║╚══██╔══╝╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗  ██║╚══██╔══╝
# ██║   ██║██████╔╝██║   ██║      ██║   ██║   ██║██████╔╝██████╔╝█████╗  ██╔██╗ ██║   ██║
# ██║▄▄ ██║██╔══██╗██║   ██║      ██║   ██║   ██║██╔══██╗██╔══██╗██╔══╝  ██║╚██╗██║   ██║
# ╚██████╔╝██████╔╝██║   ██║      ██║   ╚██████╔╝██║  ██║██║  ██║███████╗██║ ╚████║   ██║
#  ╚══▀▀═╝ ╚═════╝ ╚═╝   ╚═╝      ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - qbittorrent_config:/config
      - downloads:/downloads
    # PUID/PGID are now correctly sourced from the.env file
    # along with TZ and other variables.
    env_file:
      - '.env'

# Other services follow, using the same structure...

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - 9696:9696
    volumes:
      - prowlarr_config:/config
      - prowlarr_backup:/data/Backup
      - downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - sonarr_config:/config
      - sonarr_backup:/data/Backup
      - sonarr_tvshows:/tv # Mapped to media volume
      - downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'

  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    ports:
      - 8990:8989
    volumes:
      - sonarr_anime_config:/config
      - sonarr_anime_anime:/anime # Mapped to media volume
      - downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - radarr_config:/config
      - radarr_movies:/movies # Mapped to media volume
      - radarr_backup:/data/Backup
      - downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    ports:
      - 6767:6767
    volumes:
      - bazarr_config:/config
      - radarr_movies:/movies # Mapped to media volume
      - sonarr_tvshows:/tv   # Mapped to media volume
    restart: unless-stopped
    env_file:
      - '.env'

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - homarr_configs:/app/data/configs
      - homarr_icons:/app/public/icons
      - homarr_data:/data
    ports:
      - '7575:7575'
    env_file:
      - '.env'

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    volumes:
      - jellyseerr_config:/app/config
    restart: unless-stopped
    env_file:
      - '.env'

  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - emby_config:/config
      - radarr_movies:/data/movies
      - sonarr_tvshows:/data/tvshows
      - sonarr_anime_anime:/data/anime
    restart: unless-stopped
    env_file:
      - '.env'

# --- Volume Definitions ---
# Using the YAML anchor defined at the top to reuse NFS options.
# We only need to specify the unique 'device' path for each volume.
volumes:
  # --- Media and Download Volumes ---
  downloads:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DATA/Downloads"
  sonarr_tvshows:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/MEDIA/tvshows"
  sonarr_anime_anime:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/MEDIA/anime"
  radarr_movies:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/MEDIA/movies"

  # --- Application Config Volumes ---
  prowlarr_config:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Prowlarr/config"
  prowlarr_backup:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Prowlarr/backup"
  nzbget_config:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/nzbget/config"
  qbittorrent_config:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/qbittorrent/config"
  sonarr_config:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Sonarr/config"
  sonarr_backup:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Sonarr/backup"
  sonarr_anime_config:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Sonarr-Anime/config"
  radarr_config:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Radarr/config"
  radarr_backup:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Radarr/backup"
  bazarr_config:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Bazarr/config"
  homarr_configs:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Homarr/configs"
  homarr_icons:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Homarr/icons"
  homarr_data:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Homarr/data"
  jellyseerr_config:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Jellyseerr/config"
  emby_config:
    <<: *nfs-volume-opts
    driver_opts:
      device: ":/volume1/DOCKER/Arr-Stack/Emby/config"
