services:
#  ██████╗ ██╗      ██╗   ██╗███████╗████████╗██╗   ██╗███╗   ██╗
# ██╔════╝ ██║      ██║   ██║██╔════╝╚══██╔══╝██║   ██║████╗  ██║
# ██║  ███╗██║      ██║   ██║█████╗     ██║   ██║   ██║██╔██╗ ██║
# ██║   ██║██║      ██║   ██║██╔══╝     ██║   ██║   ██║██║╚██╗██║
# ╚██████╔╝███████╗╚██████╔╝███████╗   ██║   ╚██████╔╝██║ ╚████║
#  ╚═════╝ ╚══════╝ ╚═════╝ ╚══════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═══╝
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    ports:
      - 6789:6789     # NZBGet
      # - 9696:9696   # Prowlarr - Port is on the service itself
      # - 8989:8989   # Sonarr - Port is on the service itself
      # - 7878:7878   # Radarr - Port is on the service itself
      # - 5055:5055   # JellySeerr - Port is on the service itself
      - 8080:8080     # QBittorrent
      - 6881:6881     # QBittorrent
      - 6881:6881/udp # QBittorrent
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun-config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/NCVPN-PL-Warsaw-TCP.ovpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
    restart: unless-stopped
# ███╗   ██╗███████╗██████╗  ██████╗ ███████╗████████╗
# ████╗  ██║╚══███╔╝██╔══██╗██╔════╝ ██╔════╝╚══██╔══╝
# ██╔██╗ ██║  ███╔╝ ██████╔╝██║  ███╗█████╗     ██║
# ██║╚██╗██║ ███╔╝  ██╔══██╗██║   ██║██╔══╝     ██║
# ██║ ╚████║███████╗██████╔╝╚██████╔╝███████╗   ██║
# ╚═╝  ╚═══╝╚══════╝╚═════╝  ╚═════╝ ╚══════╝   ╚═╝
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    network_mode: "service:gluetun"
    environment:
      - NZBGET_USER=admin #optional
      - NZBGET_PASS=J@7713 #optional
    volumes:
      - ${ARRPATH}nzbget/config:/config
      - ${ARRPATH}Downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'



# ██████╗ ██████╗ ██╗████████╗████████╗ ██████╗ ██████╗ ██████╗ ███████╗███╗   ██╗████████╗
# ██╔═══██╗██╔══██╗██║╚══██╔══╝╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗  ██║╚══██╔══╝
# ██║   ██║██████╔╝██║   ██║      ██║   ██║   ██║██████╔╝██████╔╝█████╗  ██╔██╗ ██║   ██║
# ██║▄▄ ██║██╔══██╗██║   ██║      ██║   ██║   ██║██╔══██╗██╔══██╗██╔══╝  ██║╚██╗██║   ██║
# ╚██████╔╝██████╔╝██║   ██║      ██║   ╚██████╔╝██║  ██║██║  ██║███████╗██║ ╚████║   ██║
#  ╚══▀▀═╝ ╚═════╝ ╚═╝   ╚═╝      ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ${ARRPATH}qbittorrent/config:/config
      - ${ARRPATH}Downloads:/downloads
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    healthcheck:
      start_period: 15s
    env_file:
      - '.env'




# ██████╗   ██████╗ ████████╗
# ██╔══██╗  ██╔══██╗╚══██╔══╝
# ██║  ██║  ██║  ██║   ██║
# ██████╔╝  ██║  ██║   ██║
# ██╔══██╗  ██╔══██╗   ██║
# ██║  ████╗██████╔╝   ██║
# ╚═╝  ╚═══╝╚═════╝    ╚═╝

  rdt-client:
    image: rogerfar/rdtclient:latest
    container_name: rdt-client
    volumes:
      - ${ARRPATH}rdt-client/config:/config
      - ${ARRPATH}Downloads:/data/downloads
    ports:
      - 6500:6500
    restart: unless-stopped
    env_file:
      - '.env'



    

      

# ██████╗ ██████╗  ██████╗ ██╗   ██╗██╗      █████╗ ██████╗ ██████╗
# ██╔══██╗██╔══██╗██╔═══██╗██║   ██║██║     ██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝██████╔╝██║   ██║██║ █╗ ██║██║     ███████║██████╔╝██████╔╝
# ██╔═══╝ ██╔══██╗██║   ██║██║███╗██║██║     ██╔══██║██╔══██╗██╔══██╗
# ██║     ██║  ██║╚██████╔╝╚███╔███╔╝███████╗██║  ██║██║  ██║██║  ██║
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - 9696:9696
    volumes:
      - prowlarr_config:/config
      - prowlarr_backup:/data/Backup
      - downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'



# ███████╗ ██████╗ ███╗   ██╗ █████╗ ██████╗ ██████╗
# ██╔════╝██╔═══██╗████╗  ██║██╔══██╗██╔══██╗██╔══██╗
# ███████╗██║   ██║██╔██╗ ██║███████║██████╔╝██████╔╝
# ╚════██║██║   ██║██║╚██╗██║██╔══██║██╔══██╗██╔══██╗
# ███████║╚██████╔╝██║ ╚████║██║  ██║██║  ██║██║  ██║
# ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    #network_mode: "service:gluetun"
    ports:
      - 8989:8989
    volumes:
      - ${ARRPATH}Sonarr/config:/config
      - ${ARRPATH}Sonarr/backup:/data/Backup
      - ${ARRPATH}Sonarr/tvshows:/data/tvshows
      - ${ARRPATH}Downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'


# █████╗ ███╗   ██╗██╗███╗   ███╗███████╗ ██████╗ ██████╗
# ██╔══██╗████╗  ██║██║████╗ ████║██╔════╝██╔═══██╗██╔═══██╗
# ███████║██╔██╗ ██║██║██╔████╔██║█████╗  ██║   ██║██║   ██║
# ██╔══██║██║╚██╗██║██║██║╚██╔╝██║██╔══╝  ██║   ██║██║   ██║
# ██║  ██║██║ ╚████║██║██║ ╚═╝ ██║███████╗╚██████╔╝╚██████╔╝
# ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝╚═╝     ╚═╝╚══════╝ ╚═════╝  ╚═════╝

  sonarr-anime:
    image: linuxserver/sonarr:latest
    container_name: sonarr-anime
    #network_mode: "service:gluetun"
    ports:
      - 8990:8989 # Using port 8990 to avoid conflict with the other Sonarr
    volumes:
      - ${ARRPATH}Sonarr-Anime/config:/config
      - ${ARRPATH}Sonarr-Anime/anime:/data/anime # <-- Points to your new anime library folder
      - ${ARRPATH}Downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'



# ██████╗  █████╗ ██████╗  █████╗ ██████╗ ██████╗
# ██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝███████║██║  ██║███████║██████╔╝██████╔╝
# ██╔══██╗██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    #network_mode: "service:gluetun"
    ports:
      - 7878:7878
    volumes:
      - ${ARRPATH}Radarr/config:/config
      - ${ARRPATH}Radarr/movies:/data/movies
      - ${ARRPATH}Radarr/backup:/data/Backup
      - ${ARRPATH}Downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'



# ██████╗  █████╗ ███████╗ █████╗ ██████╗ ██████╗
# ██╔══██╗██╔══██╗╚══███╔╝██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝███████║  ███╔╝ ███████║██████╔╝██████╔╝
# ██╔══██╗██╔══██║ ███╔╝  ██╔══██║██╔══██╗██╔══██╗
# ██████╔╝██║  ██║███████╗██║  ██║██║  ██║██║  ██║
# ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    volumes:
      - ${ARRPATH}Bazarr/config:/config
      - ${ARRPATH}Radarr/movies:/movies
      - ${ARRPATH}Sonarr/tvshows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    env_file:
      - '.env'


# ██╗  ██╗ ██████╗ ███╗   ███╗ █████╗ ██████╗ ██████╗
# ██║  ██║██╔═══██╗████╗ ████║██╔══██╗██╔══██╗██╔══██╗
# ███████║██║   ██║██╔████╔██║███████║██████╔╝██████╔╝
# ██╔══██║██║   ██║██║╚██╔╝██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ${ARRPATH}Homarr/configs:/app/data/configs
      - ${ARRPATH}Homarr/icons:/app/public/icons
      - ${ARRPATH}Homarr/data:/data
    ports:
      - '7575:7575'
    env_file:
      - '.env'



#     ██╗███████╗██╗     ██╗  ██╗   ██╗███████╗███████╗███████╗██████╗ ██████╗
#     ██║██╔════╝██║     ██║  ╚██╗ ██╔╝██╔════╝██╔════╝██╔════╝██╔══██╗██╔══██╗
#     ██║█████╗  ██║     ██║   ╚████╔╝ ███████╗█████╗  █████╗  ██████╔╝██████╔╝
# ██  ██║██╔══╝  ██║     ██║    ╚██╔╝  ╚════██║██╔══╝  ██╔══╝  ██╔══██╗██╔══██╗
# ╚█████╔╝███████╗███████╗███████╗██║   ███████║███████╗███████╗██║  ██║██║  ██║
#  ╚════╝ ╚══════╝╚══════╝╚══════╝╚═╝   ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝


  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    #network_mode: "service:gluetun"
    ports:
      - 5055:5055
    volumes:
      - ${ARRPATH}JellySeerr/config:/app/config
    restart: unless-stopped
    env_file:
      - '.env'



      
      


# ██╗      ██╗██████╗  █████╗ ██████╗ ██████╗
# ██║      ██║██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██║      ██║██║  ██║███████║██████╔╝██████╔╝
# ██║      ██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ███████╗██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚══════╝╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
#  lidarr:
#    image: linuxserver/lidarr:latest
#    container_name: lidarr
#    #network_mode: "service:gluetun"
#    ports:
#      - 8686:8686
#    volumes:
#      - ${ARRPATH}Lidarr/config:/config
#      - ${ARRPATH}Lidarr/music:/data/musicfolder
#      - ${ARRPATH}Downloads:/downloads
#    restart: unless-stopped
#    env_file:
#      - '.env'



# ██████╗ ███████╗ █████╗ ██████╗  █████╗ ██████╗ ██████╗
# ██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝█████╗   ███████║██║  ██║███████║██████╔╝██████╔╝
# ██╔══██╗██╔══╝   ██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║███████╗██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
#  readarr:
#    image: linuxserver/readarr:develop
#    container_name: readarr
#    #network_mode: "service:gluetun"
#    ports:
#      - 8787:8787
#    volumes:
#      - ${ARRPATH}Readarr/config:/config
#      - ${ARRPATH}Readarr/books:/data/books
#      - ${ARRPATH}Downloads:/downloads
#    restart: unless-stopped
#    env_file:
#      - '.env'




#   ██████╗  █████╗ ██╗      ██╗██████╗  ██████╗  ███████╗
#  ██╔════╝ ██╔══██╗██║      ██║██╔══██╗ ██╔══██╗ ██╔════╝
#  ██║     ███████║██║      ██║██████╔╝ ██████╔╝ █████╗
#  ██║     ██╔══██║██║      ██║██╔══██╗ ██╔══██╗ ██╔══╝
#  ╚██████╗██║  ██║███████╗ ██║██████╔╝ ██║  ██║ ███████╗
#   ╚═════╝╚═╝  ╚═╝╚══════╝ ╚═╝╚═════╝  ╚═╝  ╚═╝ ╚══════╝
#  calibre:
#    image: lscr.io/linuxserver/calibre:latest
#    container_name: calibre
#    volumes:
#      - ${ARRPATH}Calibre/config:/config
#      - ${ARRPATH}Readarr/books:/data/Books
#      - /mnt/usbMedia01:/mnt/usbMedia01
#      - /mnt/usbMedia02:/mnt/usbMedia02
#      - /mnt/usbMedia03:/mnt/usbMedia03
#    ports:
#      - 8080:8080
#      - 8181:8181
#      - 8081:8081
#    restart: unless-stopped
#
#
#
# ██████╗ ██╗    ███████╗██╗  ██╗
# ██╔══██╗██║    ██╔════╝╚██╗██╔╝
# ██████╔╝██║    █████╗    ╚███╔╝
# ██╔═══╝ ██║    ██╔══╝    ██╔██╗
# ██║     ███████╗███████╗██╔╝ ██╗
# ╚═╝     ╚══════╝╚══════╝╚═╝  ╚═╝
#
#
#  plex:
#    image: lscr.io/linuxserver/plex:latest
#    container_name: plex
#    network_mode: host
#    environment:
#      - VERSION=docker
#      - PLEX_CLAIM= #optional
#    volumes:
#      - ${ARRPATH}Plex/config:/config
#      - ${ARRPATH}Radarr/movies:/data/Movies
#      - ${ARRPATH}Sonarr/tvshows:/data/TVShows
#    restart: unless-stopped
#
#
#
#








    # ███████╗███╗   ██╗██████╗  ██╗   ██╗
# ██╔════╝████╗ ████║██╔══██╗ ╚██╗ ██╔╝
# █████╗  ██╔████╔██║██████╔╝  ╚████╔╝
# ██╔══╝  ██║╚██╔╝██║██╔══██╗   ╚██╔╝
# ███████╗██║ ╚═╝ ██║██████╔╝    ██║
# ╚══════╝╚═╝     ╚═╝╚═════╝     ╚═╝
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby

    volumes:
    - ${ARRPATH}Emby/config:/config
    - ${ARRPATH}Radarr/movies:/data/movies
    - ${ARRPATH}Sonarr/tvshows:/data/tvshows
    - ${ARRPATH}Sonarr-Anime/anime:/data/anime 
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
    env_file:
      - '.env'



volumes:
  prowlarr_config:
    driver_opts:
      type: nfs
      o: "addr=10.20.10.27,rw,nolock,soft"  #<-- REPLACE WITH YOUR SYNOLOGY'S IP
      device: ":/volume1/DATA/Prowlarr/config" #<-- REPLACE with your Mount Path + subfolder

  prowlarr_backup:
    driver_opts:
      type: nfs
      o: "addr=10.20.10.27,rw,nolock,soft"
      device: ":/volume1/DATA/Prowlarr/backup"

  downloads:
    driver_opts:
      type: nfs
      o: "addr=10.20.10.27,rw,nolock,soft"
      device: ":/volume1/DATA/Downloads"



